version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mono_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mono_db
      MYSQL_USER: mono_user
      MYSQL_PASSWORD: mono1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mono_network

  app:
    build:
      context: ../  
      dockerfile: docker/Dockerfile
    container_name: mono_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: mono_user
      DB_PASSWORD: mono1234
      DB_NAME: mono_db
    volumes:
      - ../:/app
    working_dir: /app
    networks:
      - mono_network

volumes:
  db_data:

networks:
  mono_network:
